### ISSUE TITLE
Using Cocoapods – Images not appearing

### ISSUE THREAD

**Issue by thehexagon** [alextrob/ARChromeActivity#14] opened 2015-04-22 19:06 UTC
I'm using ARChromeActivity with Cocoapods 0.37 in a Swift project. The images don't seem to appear. I believe it's an issue with the image source not interacting properly with the framework bundle. It seems to work in TUSafariActivity, though using their approach in ARChromeActivity didn't seem to work either. Does anybody have a fix? Thanks!

**Comment by nolanw** [comment] 2015-08-03 16:41
@thehexagon If you want a dumb, quick fix, drag the `ARChromeActivity*.png` images from the `Pods` folder into your Xcode project and add them to your app target (untick the "copy if needed" box).

**Comment by anscho** [comment] 2015-12-24 16:37
Hey @thehexagon. The TUSafariActivity approach worked for me. Thank you for suggesting that - I opened up https://github.com/alextrob/ARChromeActivity/pull/23. If that solution isn't working for you, it'd be great if you could let me know what the problem is so I can improve it.

**Comment by alextrob** [comment] 2016-01-12 22:28
Thanks folks. Should be fixed in version 1.0.6.

**Closed by alextrob** 2016-01-12 22:28 UTC
